# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './pymepix-viewer/pymepixviewer/panels/ui/acqconfig.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(334, 308)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_sophy_config = QtWidgets.QLabel(self.groupBox_3)
        self.label_sophy_config.setObjectName("label_sophy_config")
        self.horizontalLayout.addWidget(self.label_sophy_config)
        self.sophy_config = QtWidgets.QLineEdit(self.groupBox_3)
        self.sophy_config.setEnabled(False)
        self.sophy_config.setObjectName("sophy_config")
        self.horizontalLayout.addWidget(self.sophy_config)
        self.open_sophy_config = QtWidgets.QPushButton(self.groupBox_3)
        self.open_sophy_config.setObjectName("open_sophy_config")
        self.horizontalLayout.addWidget(self.open_sophy_config)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.bias_voltage = QtWidgets.QSpinBox(self.groupBox_3)
        self.bias_voltage.setPrefix("")
        self.bias_voltage.setMinimum(12)
        self.bias_voltage.setMaximum(104)
        self.bias_voltage.setProperty("value", 50)
        self.bias_voltage.setObjectName("bias_voltage")
        self.horizontalLayout_16.addWidget(self.bias_voltage)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.fine_threshold = QtWidgets.QSpinBox(self.groupBox_3)
        self.fine_threshold.setMaximum(511)
        self.fine_threshold.setObjectName("fine_threshold")
        self.horizontalLayout_18.addWidget(self.fine_threshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.coarse_threshold = QtWidgets.QSpinBox(self.groupBox_3)
        self.coarse_threshold.setMaximum(15)
        self.coarse_threshold.setObjectName("coarse_threshold")
        self.horizontalLayout_19.addWidget(self.coarse_threshold)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.path_name = QtWidgets.QLineEdit(self.groupBox_3)
        self.path_name.setObjectName("path_name")
        self.horizontalLayout_4.addWidget(self.path_name)
        self.openpath = QtWidgets.QPushButton(self.groupBox_3)
        self.openpath.setObjectName("openpath")
        self.horizontalLayout_4.addWidget(self.openpath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.file_prefix = QtWidgets.QLineEdit(self.groupBox_3)
        self.file_prefix.setWhatsThis("")
        self.file_prefix.setObjectName("file_prefix")
        self.horizontalLayout_5.addWidget(self.file_prefix)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.startIndex = QtWidgets.QLCDNumber(self.groupBox_3)
        self.startIndex.setObjectName("startIndex")
        self.horizontalLayout_12.addWidget(self.startIndex)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "Acquisition"))
        self.label_sophy_config.setText(_translate("Form", "SoPhy Config"))
        self.open_sophy_config.setText(_translate("Form", "Open"))
        self.label_17.setText(_translate("Form", "Bias Voltage"))
        self.bias_voltage.setSuffix(_translate("Form", " V"))
        self.label_19.setText(_translate("Form", "Fine Threshold  [0, 511]"))
        self.label_20.setText(_translate("Form", "Coarse Threshold [0, 15]"))
        self.label_6.setText(_translate("Form", "Path"))
        self.openpath.setText(_translate("Form", "Open"))
        self.label_7.setText(_translate("Form", "Prefix:"))
        self.file_prefix.setToolTip(_translate("Form", "prefix must not contain \"_\""))
        self.file_prefix.setText(_translate("Form", "test"))
        self.label_14.setText(_translate("Form", "Index"))

