# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'daqcontrol.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 146)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.elapsed_time_h = QtWidgets.QLCDNumber(Form)
        self.elapsed_time_h.setLineWidth(1)
        self.elapsed_time_h.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elapsed_time_h.setObjectName("elapsed_time_h")
        self.horizontalLayout.addWidget(self.elapsed_time_h)
        self.elapsed_time_m = QtWidgets.QLCDNumber(Form)
        self.elapsed_time_m.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elapsed_time_m.setObjectName("elapsed_time_m")
        self.horizontalLayout.addWidget(self.elapsed_time_m)
        self.elapsed_time_s = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.elapsed_time_s.setFont(font)
        self.elapsed_time_s.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.elapsed_time_s.setObjectName("elapsed_time_s")
        self.horizontalLayout.addWidget(self.elapsed_time_s)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_acq = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_acq.sizePolicy().hasHeightForWidth())
        self.start_acq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.start_acq.setFont(font)
        self.start_acq.setObjectName("start_acq")
        self.verticalLayout.addWidget(self.start_acq)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.acquisitiontime = QtWidgets.QLineEdit(Form)
        self.acquisitiontime.setObjectName("acquisitiontime")
        self.horizontalLayout_4.addWidget(self.acquisitiontime)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_12 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.text_status = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_status.setFont(font)
        self.text_status.setObjectName("text_status")
        self.horizontalLayout_3.addWidget(self.text_status)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Elapsed"))
        self.start_acq.setText(_translate("Form", "Start Acquisition"))
        self.label_2.setText(_translate("Form", "Acquisition time (sec.):"))
        self.label_12.setText(_translate("Form", "Status:"))
        self.text_status.setText(_translate("Form", "Live"))
